import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { Nav } from "./components/nav";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FPL-Charts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container flex flex-row h-screen">
          <nav className="basis-1/5 bg-slate-700">
            <header className="p-2 pt-4">
              <h1 className="text-slate-200 text-2xl border-solid border-2 p-2 border-yellow-100">
                FPL Charts
              </h1>
            </header>
            <Nav />
          </nav>
          <div className="basis-4/5 p-4">
            <Header />
            <div className="flex">{children}</div>
            <ToastContainer
              position="bottom-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </div>
        </main>
      </body>
    </html>
  );
}
