import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FPL-Charts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container flex flex-row h-screen">
          <nav className="basis-1/5 bg-slate-700">
            <header className="p-2 pt-4">
              <h1 className="text-slate-200 text-2xl border-solid border-2 p-2 border-yellow-100">
                FPL Charts
              </h1>
            </header>
            <ul className="p-2 text-slate-200">
              <li className="pt-4 text-xl">User Performance</li>
              <li className="pl-4">
                <a href="#" className="hover:text-yellow-100">
                  Points
                </a>
              </li>
              <li className="pl-4">
                <a href="#" className="hover:text-yellow-100">
                  Rank
                </a>
              </li>
              <li className="pl-4">
                <a href="#" className="hover:text-yellow-100">
                  Team Value
                </a>
              </li>
              <li className="pl-4">
                <a href="#" className="hover:text-yellow-100">
                  Transfer
                </a>
              </li>
              <li className="pt-4">
                <a href="#" className="text-xl hover:text-yellow-100">
                  Player Performance
                </a>
              </li>
              <li className="pt-4">
                <a href="#" className="text-xl hover:text-yellow-100">
                  Team Performance
                </a>
              </li>
            </ul>
          </nav>
          <div className="basis-4/5 p-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
