const elements = {
  "1": { id: 1, web_name: "Balogun", team: "ARS", element_types: "FWD" },
  "2": { id: 2, web_name: "Cédric", team: "ARS", element_types: "DEF" },
  "3": { id: 3, web_name: "M.Elneny", team: "ARS", element_types: "MID" },
  "4": { id: 4, web_name: "Fábio Vieira", team: "ARS", element_types: "MID" },
  "5": { id: 5, web_name: "Gabriel", team: "ARS", element_types: "DEF" },
  "6": { id: 6, web_name: "Havertz", team: "ARS", element_types: "MID" },
  "7": { id: 7, web_name: "Holding", team: "CRY", element_types: "DEF" },
  "8": { id: 8, web_name: "G.Jesus", team: "ARS", element_types: "FWD" },
  "9": { id: 9, web_name: "Jorginho", team: "ARS", element_types: "MID" },
  "10": { id: 10, web_name: "Kiwior", team: "ARS", element_types: "DEF" },
  "11": { id: 11, web_name: "Marquinhos", team: "ARS", element_types: "MID" },
  "12": { id: 12, web_name: "Martinelli", team: "ARS", element_types: "MID" },
  "13": { id: 13, web_name: "Nketiah", team: "ARS", element_types: "FWD" },
  "14": { id: 14, web_name: "Ødegaard", team: "ARS", element_types: "MID" },
  "15": { id: 15, web_name: "Thomas", team: "ARS", element_types: "MID" },
  "16": { id: 16, web_name: "Pepe", team: "ARS", element_types: "MID" },
  "17": { id: 17, web_name: "Ramsdale", team: "ARS", element_types: "GKP" },
  "18": { id: 18, web_name: "Rúnarsson", team: "ARS", element_types: "GKP" },
  "19": { id: 19, web_name: "Saka", team: "ARS", element_types: "MID" },
  "20": { id: 20, web_name: "Saliba", team: "ARS", element_types: "DEF" },
  "21": { id: 21, web_name: "Sambi", team: "LUT", element_types: "MID" },
  "22": { id: 22, web_name: "Smith Rowe", team: "ARS", element_types: "MID" },
  "23": { id: 23, web_name: "Tavares", team: "NFO", element_types: "DEF" },
  "24": { id: 24, web_name: "Tierney", team: "ARS", element_types: "DEF" },
  "25": { id: 25, web_name: "Tomiyasu", team: "ARS", element_types: "DEF" },
  "26": { id: 26, web_name: "Trossard", team: "ARS", element_types: "MID" },
  "27": { id: 27, web_name: "Trusty", team: "SHU", element_types: "DEF" },
  "28": { id: 28, web_name: "Turner", team: "NFO", element_types: "GKP" },
  "29": { id: 29, web_name: "White", team: "ARS", element_types: "DEF" },
  "30": { id: 30, web_name: "Xhaka", team: "ARS", element_types: "MID" },
  "31": { id: 31, web_name: "Zinchenko", team: "ARS", element_types: "DEF" },
  "32": { id: 32, web_name: "Alex Moreno", team: "AVL", element_types: "DEF" },
  "33": { id: 33, web_name: "Archer", team: "SHU", element_types: "FWD" },
  "34": { id: 34, web_name: "Bailey", team: "AVL", element_types: "MID" },
  "35": { id: 35, web_name: "Buendia", team: "AVL", element_types: "MID" },
  "36": { id: 36, web_name: "Cash", team: "AVL", element_types: "DEF" },
  "37": { id: 37, web_name: "Chambers", team: "AVL", element_types: "DEF" },
  "38": { id: 38, web_name: "Coutinho", team: "AVL", element_types: "MID" },
  "39": { id: 39, web_name: "Davis", team: "AVL", element_types: "FWD" },
  "40": { id: 40, web_name: "Dendoncker", team: "AVL", element_types: "MID" },
  "41": { id: 41, web_name: "Diego Carlos", team: "AVL", element_types: "DEF" },
  "42": { id: 42, web_name: "Digne", team: "AVL", element_types: "DEF" },
  "43": { id: 43, web_name: "Douglas Luiz", team: "AVL", element_types: "MID" },
  "44": { id: 44, web_name: "Duran", team: "AVL", element_types: "FWD" },
  "45": { id: 45, web_name: "Hause", team: "AVL", element_types: "DEF" },
  "46": { id: 46, web_name: "Iroegbunam", team: "AVL", element_types: "MID" },
  "47": { id: 47, web_name: "Kamara", team: "AVL", element_types: "MID" },
  "48": { id: 48, web_name: "Konsa", team: "AVL", element_types: "DEF" },
  "49": { id: 49, web_name: "Martinez", team: "AVL", element_types: "GKP" },
  "50": { id: 50, web_name: "McGinn", team: "AVL", element_types: "MID" },
  "51": { id: 51, web_name: "Mings", team: "AVL", element_types: "DEF" },
  "52": { id: 52, web_name: "Nakamba", team: "LUT", element_types: "MID" },
  "53": { id: 53, web_name: "Olsen", team: "AVL", element_types: "GKP" },
  "54": { id: 54, web_name: "Philogene", team: "AVL", element_types: "MID" },
  "55": { id: 55, web_name: "J.Ramsey", team: "AVL", element_types: "MID" },
  "56": { id: 56, web_name: "Sanson", team: "AVL", element_types: "MID" },
  "57": { id: 57, web_name: "Sinisalo", team: "AVL", element_types: "GKP" },
  "58": { id: 58, web_name: "Tielemans", team: "AVL", element_types: "MID" },
  "59": {
    id: 59,
    web_name: "Bertrand Traoré",
    team: "AVL",
    element_types: "MID",
  },
  "60": { id: 60, web_name: "Watkins", team: "AVL", element_types: "FWD" },
  "61": { id: 61, web_name: "Wesley", team: "AVL", element_types: "FWD" },
  "62": { id: 62, web_name: "Anthony", team: "BOU", element_types: "MID" },
  "63": { id: 63, web_name: "Billing", team: "BOU", element_types: "MID" },
  "64": { id: 64, web_name: "Brooks", team: "BOU", element_types: "MID" },
  "65": { id: 65, web_name: "Christie", team: "BOU", element_types: "MID" },
  "66": { id: 66, web_name: "L.Cook", team: "BOU", element_types: "MID" },
  "67": { id: 67, web_name: "Siriki", team: "BOU", element_types: "MID" },
  "68": { id: 68, web_name: "Fredericks", team: "BOU", element_types: "DEF" },
  "69": { id: 69, web_name: "Hill", team: "BOU", element_types: "DEF" },
  "70": { id: 70, web_name: "Kelly", team: "BOU", element_types: "DEF" },
  "71": { id: 71, web_name: "Kilkenny", team: "BOU", element_types: "MID" },
  "72": { id: 72, web_name: "Kluivert", team: "BOU", element_types: "MID" },
  "73": { id: 73, web_name: "Lowe", team: "BOU", element_types: "MID" },
  "74": { id: 74, web_name: "Marcondes", team: "BOU", element_types: "MID" },
  "75": { id: 75, web_name: "Mepham", team: "BOU", element_types: "DEF" },
  "76": { id: 76, web_name: "Moore", team: "BOU", element_types: "FWD" },
  "77": { id: 77, web_name: "Neto", team: "BOU", element_types: "GKP" },
  "78": { id: 78, web_name: "O.Dango", team: "BOU", element_types: "MID" },
  "79": { id: 79, web_name: "Pearson", team: "BOU", element_types: "MID" },
  "80": { id: 80, web_name: "Randolph", team: "BOU", element_types: "GKP" },
  "81": { id: 81, web_name: "Rothwell", team: "BOU", element_types: "MID" },
  "82": { id: 82, web_name: "Semenyo", team: "BOU", element_types: "FWD" },
  "83": { id: 83, web_name: "Senesi", team: "BOU", element_types: "DEF" },
  "84": { id: 84, web_name: "Smith", team: "BOU", element_types: "DEF" },
  "85": { id: 85, web_name: "Solanke", team: "BOU", element_types: "FWD" },
  "86": { id: 86, web_name: "Tavernier", team: "BOU", element_types: "MID" },
  "87": { id: 87, web_name: "Hamed Traorè", team: "BOU", element_types: "MID" },
  "88": { id: 88, web_name: "Travers", team: "BOU", element_types: "GKP" },
  "89": { id: 89, web_name: "Zabarnyi", team: "BOU", element_types: "DEF" },
  "90": { id: 90, web_name: "Ajer", team: "BRE", element_types: "DEF" },
  "91": { id: 91, web_name: "Balcombe", team: "BRE", element_types: "GKP" },
  "92": { id: 92, web_name: "Baptiste", team: "BRE", element_types: "MID" },
  "93": { id: 93, web_name: "Bech", team: "BRE", element_types: "DEF" },
  "94": { id: 94, web_name: "Bidstrup", team: "BRE", element_types: "MID" },
  "95": { id: 95, web_name: "Canós", team: "BRE", element_types: "MID" },
  "96": { id: 96, web_name: "Collins", team: "BRE", element_types: "DEF" },
  "97": { id: 97, web_name: "Cox", team: "BRE", element_types: "GKP" },
  "98": { id: 98, web_name: "Damsgaard", team: "BRE", element_types: "MID" },
  "99": { id: 99, web_name: "Dasilva", team: "BRE", element_types: "MID" },
  "100": { id: 100, web_name: "Dervişoğlu", team: "BRE", element_types: "FWD" },
  "101": { id: 101, web_name: "Flekken", team: "BRE", element_types: "GKP" },
  "102": { id: 102, web_name: "Goode", team: "BRE", element_types: "DEF" },
  "103": { id: 103, web_name: "Henry", team: "BRE", element_types: "DEF" },
  "104": { id: 104, web_name: "Hickey", team: "BRE", element_types: "DEF" },
  "105": { id: 105, web_name: "Janelt", team: "BRE", element_types: "MID" },
  "106": { id: 106, web_name: "Jensen", team: "BRE", element_types: "MID" },
  "107": {
    id: 107,
    web_name: "Lewis-Potter",
    team: "BRE",
    element_types: "MID",
  },
  "108": { id: 108, web_name: "Mbeumo", team: "BRE", element_types: "MID" },
  "109": { id: 109, web_name: "Mee", team: "BRE", element_types: "DEF" },
  "110": { id: 110, web_name: "Nørgaard", team: "BRE", element_types: "MID" },
  "111": { id: 111, web_name: "Onyeka", team: "BRE", element_types: "MID" },
  "112": { id: 112, web_name: "Pinnock", team: "BRE", element_types: "DEF" },
  "113": { id: 113, web_name: "Raya", team: "ARS", element_types: "GKP" },
  "114": { id: 114, web_name: "Roerslev", team: "BRE", element_types: "DEF" },
  "115": { id: 115, web_name: "Schade", team: "BRE", element_types: "MID" },
  "116": { id: 116, web_name: "Strakosha", team: "BRE", element_types: "GKP" },
  "117": { id: 117, web_name: "Toney", team: "BRE", element_types: "FWD" },
  "118": { id: 118, web_name: "Trevitt", team: "BRE", element_types: "MID" },
  "119": { id: 119, web_name: "Wissa", team: "BRE", element_types: "FWD" },
  "120": { id: 120, web_name: "Yarmoliuk", team: "BRE", element_types: "MID" },
  "121": { id: 121, web_name: "Zanka", team: "BRE", element_types: "DEF" },
  "122": { id: 122, web_name: "Adingra", team: "BHA", element_types: "MID" },
  "123": { id: 123, web_name: "Alzate", team: "BHA", element_types: "MID" },
  "124": { id: 124, web_name: "Ayari", team: "BHA", element_types: "MID" },
  "125": { id: 125, web_name: "Buonanotte", team: "BHA", element_types: "MID" },
  "126": { id: 126, web_name: "Caicedo", team: "CHE", element_types: "MID" },
  "127": { id: 127, web_name: "Connolly", team: "BHA", element_types: "FWD" },
  "128": { id: 128, web_name: "Dahoud", team: "BHA", element_types: "MID" },
  "129": { id: 129, web_name: "Dunk", team: "BHA", element_types: "DEF" },
  "130": { id: 130, web_name: "Enciso", team: "BHA", element_types: "MID" },
  "131": { id: 131, web_name: "Estupiñan", team: "BHA", element_types: "DEF" },
  "132": { id: 132, web_name: "Ferguson", team: "BHA", element_types: "FWD" },
  "133": { id: 133, web_name: "Gilmour", team: "BHA", element_types: "MID" },
  "134": { id: 134, web_name: "Gross", team: "BHA", element_types: "MID" },
  "135": { id: 135, web_name: "João Pedro", team: "BHA", element_types: "FWD" },
  "136": { id: 136, web_name: "Karbownik", team: "BHA", element_types: "DEF" },
  "137": { id: 137, web_name: "Kozłowski", team: "BHA", element_types: "MID" },
  "138": { id: 138, web_name: "Lallana", team: "BHA", element_types: "MID" },
  "139": { id: 139, web_name: "Lamptey", team: "BHA", element_types: "DEF" },
  "140": { id: 140, web_name: "March", team: "BHA", element_types: "MID" },
  "141": { id: 141, web_name: "McGill", team: "BHA", element_types: "GKP" },
  "142": { id: 142, web_name: "Milner", team: "BHA", element_types: "MID" },
  "143": { id: 143, web_name: "Mitoma", team: "BHA", element_types: "MID" },
  "144": { id: 144, web_name: "Moder", team: "BHA", element_types: "MID" },
  "145": { id: 145, web_name: "Sanchez", team: "CHE", element_types: "GKP" },
  "146": { id: 146, web_name: "Sarmiento", team: "BHA", element_types: "MID" },
  "147": { id: 147, web_name: "Scherpen", team: "BHA", element_types: "GKP" },
  "148": { id: 148, web_name: "Steele", team: "BHA", element_types: "GKP" },
  "149": { id: 149, web_name: "Undav", team: "BHA", element_types: "FWD" },
  "150": { id: 150, web_name: "Van Hecke", team: "BHA", element_types: "DEF" },
  "151": { id: 151, web_name: "Veltman", team: "BHA", element_types: "DEF" },
  "152": { id: 152, web_name: "Verbruggen", team: "BHA", element_types: "GKP" },
  "153": { id: 153, web_name: "Webster", team: "BHA", element_types: "DEF" },
  "154": { id: 154, web_name: "Welbeck", team: "BHA", element_types: "FWD" },
  "155": { id: 155, web_name: "Zeqiri", team: "BHA", element_types: "FWD" },
  "156": { id: 156, web_name: "Agyei", team: "BUR", element_types: "MID" },
  "157": { id: 157, web_name: "Al-Dakhil", team: "BUR", element_types: "DEF" },
  "158": { id: 158, web_name: "Bastien", team: "BUR", element_types: "MID" },
  "159": { id: 159, web_name: "Benson", team: "BUR", element_types: "MID" },
  "160": { id: 160, web_name: "Beyer", team: "BUR", element_types: "DEF" },
  "161": { id: 161, web_name: "Brownhill", team: "BUR", element_types: "MID" },
  "162": { id: 162, web_name: "Churlinov", team: "BUR", element_types: "MID" },
  "163": { id: 163, web_name: "Cork", team: "BUR", element_types: "MID" },
  "164": { id: 164, web_name: "Costelloe", team: "BUR", element_types: "MID" },
  "165": { id: 165, web_name: "Cullen", team: "BUR", element_types: "MID" },
  "166": { id: 166, web_name: "Egan-Riley", team: "BUR", element_types: "DEF" },
  "167": { id: 167, web_name: "Ekdal", team: "BUR", element_types: "DEF" },
  "168": { id: 168, web_name: "Foster", team: "BUR", element_types: "FWD" },
  "169": { id: 169, web_name: "Franchi", team: "BUR", element_types: "GKP" },
  "170": {
    id: 170,
    web_name: "Gudmundsson",
    team: "BUR",
    element_types: "MID",
  },
  "171": { id: 171, web_name: "McNally", team: "BUR", element_types: "DEF" },
  "172": { id: 172, web_name: "Muric", team: "BUR", element_types: "GKP" },
  "173": { id: 173, web_name: "O'Shea", team: "BUR", element_types: "DEF" },
  "174": { id: 174, web_name: "Obafemi", team: "BUR", element_types: "FWD" },
  "175": {
    id: 175,
    web_name: "Peacock-Farrell",
    team: "BUR",
    element_types: "GKP",
  },
  "176": { id: 176, web_name: "Roberts", team: "BUR", element_types: "DEF" },
  "177": { id: 177, web_name: "Rodriguez", team: "BUR", element_types: "FWD" },
  "178": { id: 178, web_name: "Taylor", team: "BUR", element_types: "DEF" },
  "179": { id: 179, web_name: "Thomas", team: "BUR", element_types: "DEF" },
  "180": { id: 180, web_name: "Twine", team: "BUR", element_types: "MID" },
  "181": { id: 181, web_name: "Vigouroux", team: "BUR", element_types: "GKP" },
  "182": { id: 182, web_name: "Vitinho", team: "BUR", element_types: "DEF" },
  "183": { id: 183, web_name: "Weghorst", team: "BUR", element_types: "FWD" },
  "184": { id: 184, web_name: "Zaroury", team: "BUR", element_types: "MID" },
  "185": { id: 185, web_name: "Ampadu", team: "CHE", element_types: "DEF" },
  "186": { id: 186, web_name: "Andrey", team: "CHE", element_types: "MID" },
  "187": {
    id: 187,
    web_name: "Arrizabalaga",
    team: "CHE",
    element_types: "GKP",
  },
  "188": { id: 188, web_name: "Aubameyang", team: "CHE", element_types: "FWD" },
  "189": {
    id: 189,
    web_name: "Azpilicueta",
    team: "CHE",
    element_types: "DEF",
  },
  "190": { id: 190, web_name: "Baba", team: "CHE", element_types: "DEF" },
  "191": {
    id: 191,
    web_name: "B.Badiashile",
    team: "CHE",
    element_types: "DEF",
  },
  "192": { id: 192, web_name: "Bettinelli", team: "CHE", element_types: "GKP" },
  "193": { id: 193, web_name: "Broja", team: "CHE", element_types: "FWD" },
  "194": { id: 194, web_name: "Chalobah", team: "CHE", element_types: "DEF" },
  "195": { id: 195, web_name: "Chilwell", team: "CHE", element_types: "DEF" },
  "196": {
    id: 196,
    web_name: "Chukwuemeka",
    team: "CHE",
    element_types: "MID",
  },
  "197": { id: 197, web_name: "Colwill", team: "CHE", element_types: "DEF" },
  "198": { id: 198, web_name: "Cucurella", team: "CHE", element_types: "DEF" },
  "199": { id: 199, web_name: "Enzo", team: "CHE", element_types: "MID" },
  "200": { id: 200, web_name: "D.D.Fofana", team: "CHE", element_types: "FWD" },
  "201": { id: 201, web_name: "W.Fofana", team: "CHE", element_types: "DEF" },
  "202": { id: 202, web_name: "Gallagher", team: "CHE", element_types: "MID" },
  "203": { id: 203, web_name: "Gusto", team: "CHE", element_types: "DEF" },
  "204": { id: 204, web_name: "Hall", team: "NEW", element_types: "DEF" },
  "205": {
    id: 205,
    web_name: "Hudson-Odoi",
    team: "NFO",
    element_types: "MID",
  },
  "206": { id: 206, web_name: "James", team: "CHE", element_types: "DEF" },
  "207": { id: 207, web_name: "Lukaku", team: "CHE", element_types: "FWD" },
  "208": { id: 208, web_name: "Madueke", team: "CHE", element_types: "MID" },
  "209": { id: 209, web_name: "Mount", team: "MUN", element_types: "MID" },
  "210": { id: 210, web_name: "Mudryk", team: "CHE", element_types: "MID" },
  "211": { id: 211, web_name: "N.Jackson", team: "CHE", element_types: "FWD" },
  "212": { id: 212, web_name: "Nkunku", team: "CHE", element_types: "FWD" },
  "213": { id: 213, web_name: "Pulisic", team: "CHE", element_types: "MID" },
  "214": { id: 214, web_name: "M.Sarr", team: "CHE", element_types: "DEF" },
  "215": { id: 215, web_name: "Slonina", team: "CHE", element_types: "GKP" },
  "216": { id: 216, web_name: "Sterling", team: "CHE", element_types: "MID" },
  "217": { id: 217, web_name: "T.Silva", team: "CHE", element_types: "DEF" },
  "218": { id: 218, web_name: "Ziyech", team: "CHE", element_types: "MID" },
  "219": { id: 219, web_name: "Ahamada", team: "CRY", element_types: "MID" },
  "220": { id: 220, web_name: "Andersen", team: "CRY", element_types: "DEF" },
  "221": { id: 221, web_name: "J.Ayew", team: "CRY", element_types: "MID" },
  "222": { id: 222, web_name: "Clyne", team: "CRY", element_types: "DEF" },
  "223": { id: 223, web_name: "C.Doucouré", team: "CRY", element_types: "MID" },
  "224": { id: 224, web_name: "Ebiowei", team: "CRY", element_types: "MID" },
  "225": { id: 225, web_name: "Edouard", team: "CRY", element_types: "FWD" },
  "226": { id: 226, web_name: "Eze", team: "CRY", element_types: "MID" },
  "227": { id: 227, web_name: "Guaita", team: "CRY", element_types: "GKP" },
  "228": { id: 228, web_name: "Guéhi", team: "CRY", element_types: "DEF" },
  "229": { id: 229, web_name: "Hughes", team: "CRY", element_types: "MID" },
  "230": { id: 230, web_name: "Johnstone", team: "CRY", element_types: "GKP" },
  "231": { id: 231, web_name: "Lerma", team: "CRY", element_types: "MID" },
  "232": { id: 232, web_name: "Mateta", team: "CRY", element_types: "FWD" },
  "233": { id: 233, web_name: "Matthews", team: "CRY", element_types: "GKP" },
  "234": { id: 234, web_name: "Mitchell", team: "CRY", element_types: "DEF" },
  "235": { id: 235, web_name: "O'Brien", team: "CRY", element_types: "DEF" },
  "236": { id: 236, web_name: "Olise", team: "CRY", element_types: "MID" },
  "237": { id: 237, web_name: "Plange", team: "CRY", element_types: "FWD" },
  "238": { id: 238, web_name: "C.Richards", team: "CRY", element_types: "DEF" },
  "239": { id: 239, web_name: "Riedewald", team: "CRY", element_types: "MID" },
  "240": { id: 240, web_name: "Schlupp", team: "CRY", element_types: "MID" },
  "241": { id: 241, web_name: "Tomkins", team: "CRY", element_types: "DEF" },
  "242": { id: 242, web_name: "Ward", team: "CRY", element_types: "DEF" },
  "243": { id: 243, web_name: "Whitworth", team: "CRY", element_types: "GKP" },
  "244": {
    id: 244,
    web_name: "André Gomes",
    team: "EVE",
    element_types: "MID",
  },
  "245": {
    id: 245,
    web_name: "Branthwaite",
    team: "EVE",
    element_types: "DEF",
  },
  "246": {
    id: 246,
    web_name: "Calvert-Lewin",
    team: "EVE",
    element_types: "FWD",
  },
  "247": { id: 247, web_name: "Coleman", team: "EVE", element_types: "DEF" },
  "248": { id: 248, web_name: "Dele", team: "EVE", element_types: "MID" },
  "249": { id: 249, web_name: "A.Doucoure", team: "EVE", element_types: "MID" },
  "250": { id: 250, web_name: "Garner", team: "EVE", element_types: "MID" },
  "251": { id: 251, web_name: "Gbamin", team: "EVE", element_types: "MID" },
  "252": { id: 252, web_name: "Godfrey", team: "EVE", element_types: "DEF" },
  "253": { id: 253, web_name: "Gray", team: "EVE", element_types: "MID" },
  "254": { id: 254, web_name: "Gana", team: "EVE", element_types: "MID" },
  "255": { id: 255, web_name: "Holgate", team: "EVE", element_types: "DEF" },
  "256": { id: 256, web_name: "Iwobi", team: "FUL", element_types: "MID" },
  "257": { id: 257, web_name: "Keane", team: "EVE", element_types: "DEF" },
  "258": { id: 258, web_name: "Maupay", team: "BRE", element_types: "FWD" },
  "259": { id: 259, web_name: "McNeil", team: "EVE", element_types: "MID" },
  "260": { id: 260, web_name: "Mykolenko", team: "EVE", element_types: "DEF" },
  "261": { id: 261, web_name: "Onana", team: "EVE", element_types: "MID" },
  "262": { id: 262, web_name: "Patterson", team: "EVE", element_types: "DEF" },
  "263": { id: 263, web_name: "Pickford", team: "EVE", element_types: "GKP" },
  "264": { id: 264, web_name: "Simms", team: "EVE", element_types: "FWD" },
  "265": { id: 265, web_name: "Tarkowski", team: "EVE", element_types: "DEF" },
  "266": { id: 266, web_name: "J.Virginia", team: "EVE", element_types: "GKP" },
  "267": { id: 267, web_name: "Andreas", team: "FUL", element_types: "MID" },
  "268": { id: 268, web_name: "Cairney", team: "FUL", element_types: "MID" },
  "269": {
    id: 269,
    web_name: "I.Cavaleiro",
    team: "FUL",
    element_types: "MID",
  },
  "270": {
    id: 270,
    web_name: "De Cordova-Reid",
    team: "FUL",
    element_types: "MID",
  },
  "271": { id: 271, web_name: "Diop", team: "FUL", element_types: "DEF" },
  "272": { id: 272, web_name: "Francois", team: "FUL", element_types: "MID" },
  "273": { id: 273, web_name: "Knockaert", team: "FUL", element_types: "MID" },
  "274": { id: 274, web_name: "Kongolo", team: "FUL", element_types: "DEF" },
  "275": { id: 275, web_name: "Leno", team: "FUL", element_types: "GKP" },
  "276": { id: 276, web_name: "Lukić", team: "FUL", element_types: "MID" },
  "277": { id: 277, web_name: "Mbabu", team: "FUL", element_types: "DEF" },
  "278": { id: 278, web_name: "Mitrović", team: "FUL", element_types: "FWD" },
  "279": { id: 279, web_name: "Muniz", team: "FUL", element_types: "FWD" },
  "280": { id: 280, web_name: "J.Palhinha", team: "FUL", element_types: "MID" },
  "281": { id: 281, web_name: "Ream", team: "FUL", element_types: "DEF" },
  "282": { id: 282, web_name: "Reed", team: "FUL", element_types: "MID" },
  "283": { id: 283, web_name: "Robinson", team: "FUL", element_types: "DEF" },
  "284": { id: 284, web_name: "Rodák", team: "FUL", element_types: "GKP" },
  "285": { id: 285, web_name: "Tete", team: "FUL", element_types: "DEF" },
  "286": { id: 286, web_name: "Tosin", team: "FUL", element_types: "DEF" },
  "287": { id: 287, web_name: "Vinícius", team: "FUL", element_types: "FWD" },
  "288": { id: 288, web_name: "Wilson", team: "FUL", element_types: "MID" },
  "289": { id: 289, web_name: "Adrián", team: "LIV", element_types: "GKP" },
  "290": {
    id: 290,
    web_name: "Alexander-Arnold",
    team: "LIV",
    element_types: "DEF",
  },
  "291": { id: 291, web_name: "A.Becker", team: "LIV", element_types: "GKP" },
  "292": { id: 292, web_name: "Bajcetic", team: "LIV", element_types: "MID" },
  "293": { id: 293, web_name: "Darwin", team: "LIV", element_types: "FWD" },
  "294": { id: 294, web_name: "Diogo J.", team: "LIV", element_types: "MID" },
  "295": { id: 295, web_name: "Elliott", team: "LIV", element_types: "MID" },
  "296": { id: 296, web_name: "Fabinho", team: "LIV", element_types: "MID" },
  "297": { id: 297, web_name: "Gakpo", team: "LIV", element_types: "FWD" },
  "298": { id: 298, web_name: "Gomez", team: "LIV", element_types: "DEF" },
  "299": { id: 299, web_name: "Henderson", team: "LIV", element_types: "MID" },
  "300": { id: 300, web_name: "Jones", team: "LIV", element_types: "MID" },
  "301": { id: 301, web_name: "Kelleher", team: "LIV", element_types: "GKP" },
  "302": { id: 302, web_name: "Konaté", team: "LIV", element_types: "DEF" },
  "303": { id: 303, web_name: "Luis Díaz", team: "LIV", element_types: "MID" },
  "304": {
    id: 304,
    web_name: "Mac Allister",
    team: "LIV",
    element_types: "MID",
  },
  "305": { id: 305, web_name: "Matip", team: "LIV", element_types: "DEF" },
  "306": { id: 306, web_name: "Phillips", team: "LIV", element_types: "DEF" },
  "307": { id: 307, web_name: "Robertson", team: "LIV", element_types: "DEF" },
  "308": { id: 308, web_name: "Salah", team: "LIV", element_types: "MID" },
  "309": { id: 309, web_name: "Szoboszlai", team: "LIV", element_types: "MID" },
  "310": { id: 310, web_name: "Thiago", team: "LIV", element_types: "MID" },
  "311": { id: 311, web_name: "Tsimikas", team: "LIV", element_types: "DEF" },
  "312": {
    id: 312,
    web_name: "Van den Berg",
    team: "LIV",
    element_types: "DEF",
  },
  "313": { id: 313, web_name: "Virgil", team: "LIV", element_types: "DEF" },
  "314": { id: 314, web_name: "Adebayo", team: "LUT", element_types: "FWD" },
  "315": { id: 315, web_name: "Andersen", team: "LUT", element_types: "DEF" },
  "316": { id: 316, web_name: "Bell", team: "LUT", element_types: "DEF" },
  "317": { id: 317, web_name: "Berry", team: "LUT", element_types: "MID" },
  "318": { id: 318, web_name: "Burke", team: "LUT", element_types: "DEF" },
  "319": { id: 319, web_name: "Campbell", team: "LUT", element_types: "MID" },
  "320": { id: 320, web_name: "Clark", team: "LUT", element_types: "MID" },
  "321": { id: 321, web_name: "Doughty", team: "LUT", element_types: "DEF" },
  "322": { id: 322, web_name: "Freeman", team: "LUT", element_types: "MID" },
  "323": { id: 323, web_name: "Macey", team: "LUT", element_types: "GKP" },
  "324": { id: 324, web_name: "McAtee", team: "LUT", element_types: "FWD" },
  "325": { id: 325, web_name: "Mendes", team: "LUT", element_types: "MID" },
  "326": { id: 326, web_name: "Morris", team: "LUT", element_types: "FWD" },
  "327": { id: 327, web_name: "Muskwe", team: "LUT", element_types: "FWD" },
  "328": { id: 328, web_name: "Ogbene", team: "LUT", element_types: "FWD" },
  "329": { id: 329, web_name: "Onyedinma", team: "LUT", element_types: "MID" },
  "330": { id: 330, web_name: "Osho", team: "LUT", element_types: "DEF" },
  "331": { id: 331, web_name: "Pepple", team: "LUT", element_types: "FWD" },
  "332": { id: 332, web_name: "Pereira", team: "LUT", element_types: "MID" },
  "333": { id: 333, web_name: "Potts", team: "LUT", element_types: "DEF" },
  "334": { id: 334, web_name: "Rea", team: "LUT", element_types: "MID" },
  "335": { id: 335, web_name: "Shea", team: "LUT", element_types: "GKP" },
  "336": { id: 336, web_name: "Taylor", team: "LUT", element_types: "FWD" },
  "337": { id: 337, web_name: "Thorpe", team: "LUT", element_types: "MID" },
  "338": { id: 338, web_name: "Walton", team: "LUT", element_types: "GKP" },
  "339": { id: 339, web_name: "Watson", team: "LUT", element_types: "MID" },
  "340": { id: 340, web_name: "Woodrow", team: "LUT", element_types: "FWD" },
  "341": { id: 341, web_name: "Akanji", team: "MCI", element_types: "DEF" },
  "342": { id: 342, web_name: "Aké", team: "MCI", element_types: "DEF" },
  "343": { id: 343, web_name: "J.Alvarez", team: "MCI", element_types: "FWD" },
  "344": { id: 344, web_name: "Bernardo", team: "MCI", element_types: "MID" },
  "345": { id: 345, web_name: "Bobb", team: "MCI", element_types: "MID" },
  "346": { id: 346, web_name: "Cancelo", team: "MCI", element_types: "DEF" },
  "347": { id: 347, web_name: "Carson", team: "MCI", element_types: "GKP" },
  "348": { id: 348, web_name: "Charles", team: "MCI", element_types: "MID" },
  "349": { id: 349, web_name: "De Bruyne", team: "MCI", element_types: "MID" },
  "350": { id: 350, web_name: "Rúben", team: "MCI", element_types: "DEF" },
  "351": { id: 351, web_name: "Doyle", team: "WOL", element_types: "MID" },
  "352": { id: 352, web_name: "Ederson M.", team: "MCI", element_types: "GKP" },
  "353": { id: 353, web_name: "Foden", team: "MCI", element_types: "MID" },
  "354": { id: 354, web_name: "Grealish", team: "MCI", element_types: "MID" },
  "355": { id: 355, web_name: "Haaland", team: "MCI", element_types: "FWD" },
  "356": { id: 356, web_name: "Kovačić", team: "MCI", element_types: "MID" },
  "357": { id: 357, web_name: "Laporte", team: "MCI", element_types: "DEF" },
  "358": { id: 358, web_name: "R.Lewis", team: "MCI", element_types: "DEF" },
  "359": { id: 359, web_name: "Mahrez", team: "MCI", element_types: "MID" },
  "360": { id: 360, web_name: "McAtee", team: "SHU", element_types: "MID" },
  "361": {
    id: 361,
    web_name: "Ortega Moreno",
    team: "MCI",
    element_types: "GKP",
  },
  "362": { id: 362, web_name: "Palmer", team: "CHE", element_types: "MID" },
  "363": { id: 363, web_name: "Perrone", team: "MCI", element_types: "MID" },
  "364": { id: 364, web_name: "Phillips", team: "MCI", element_types: "MID" },
  "365": { id: 365, web_name: "Rodrigo", team: "MCI", element_types: "MID" },
  "366": {
    id: 366,
    web_name: "Sergio Gómez",
    team: "MCI",
    element_types: "DEF",
  },
  "367": { id: 367, web_name: "Steffen", team: "MCI", element_types: "GKP" },
  "368": { id: 368, web_name: "Stones", team: "MCI", element_types: "DEF" },
  "369": { id: 369, web_name: "Walker", team: "MCI", element_types: "DEF" },
  "370": {
    id: 370,
    web_name: "Alex Telles",
    team: "MUN",
    element_types: "DEF",
  },
  "371": { id: 371, web_name: "Amad", team: "MUN", element_types: "MID" },
  "372": { id: 372, web_name: "Antony", team: "MUN", element_types: "MID" },
  "373": {
    id: 373,
    web_name: "B.Fernandes",
    team: "MUN",
    element_types: "MID",
  },
  "374": { id: 374, web_name: "B.Williams", team: "MUN", element_types: "DEF" },
  "375": { id: 375, web_name: "Bailly", team: "MUN", element_types: "DEF" },
  "376": { id: 376, web_name: "Casemiro", team: "MUN", element_types: "MID" },
  "377": { id: 377, web_name: "Dalot", team: "MUN", element_types: "DEF" },
  "378": { id: 378, web_name: "Elanga", team: "NFO", element_types: "MID" },
  "379": { id: 379, web_name: "Eriksen", team: "MUN", element_types: "MID" },
  "380": { id: 380, web_name: "Fernandez", team: "MUN", element_types: "DEF" },
  "381": { id: 381, web_name: "Fred", team: "MUN", element_types: "MID" },
  "382": { id: 382, web_name: "Garnacho", team: "MUN", element_types: "MID" },
  "383": { id: 383, web_name: "Hannibal", team: "MUN", element_types: "MID" },
  "384": { id: 384, web_name: "Heaton", team: "MUN", element_types: "GKP" },
  "385": { id: 385, web_name: "Henderson", team: "CRY", element_types: "GKP" },
  "386": { id: 386, web_name: "Lindelof", team: "MUN", element_types: "DEF" },
  "387": { id: 387, web_name: "Maguire", team: "MUN", element_types: "DEF" },
  "388": { id: 388, web_name: "Mainoo", team: "MUN", element_types: "MID" },
  "389": { id: 389, web_name: "Malacia", team: "MUN", element_types: "DEF" },
  "390": { id: 390, web_name: "Martial", team: "MUN", element_types: "FWD" },
  "391": { id: 391, web_name: "Martinez", team: "MUN", element_types: "DEF" },
  "392": { id: 392, web_name: "McTominay", team: "MUN", element_types: "MID" },
  "393": { id: 393, web_name: "Mengi", team: "LUT", element_types: "DEF" },
  "394": { id: 394, web_name: "Pellistri", team: "MUN", element_types: "MID" },
  "395": { id: 395, web_name: "R.Varane", team: "MUN", element_types: "DEF" },
  "396": { id: 396, web_name: "Rashford", team: "MUN", element_types: "MID" },
  "397": { id: 397, web_name: "Sancho", team: "MUN", element_types: "MID" },
  "398": { id: 398, web_name: "Shaw", team: "MUN", element_types: "DEF" },
  "399": { id: 399, web_name: "Shoretire", team: "MUN", element_types: "FWD" },
  "400": {
    id: 400,
    web_name: "Van de Beek",
    team: "MUN",
    element_types: "MID",
  },
  "401": {
    id: 401,
    web_name: "Wan-Bissaka",
    team: "MUN",
    element_types: "DEF",
  },
  "402": { id: 402, web_name: "Almirón", team: "NEW", element_types: "MID" },
  "403": { id: 403, web_name: "Anderson", team: "NEW", element_types: "MID" },
  "404": { id: 404, web_name: "Ashby", team: "NEW", element_types: "DEF" },
  "405": { id: 405, web_name: "Botman", team: "NEW", element_types: "DEF" },
  "406": { id: 406, web_name: "Bruno G.", team: "NEW", element_types: "MID" },
  "407": { id: 407, web_name: "Burn", team: "NEW", element_types: "DEF" },
  "408": { id: 408, web_name: "Darlow", team: "NEW", element_types: "GKP" },
  "409": { id: 409, web_name: "Dubravka", team: "NEW", element_types: "GKP" },
  "410": { id: 410, web_name: "Fraser", team: "NEW", element_types: "MID" },
  "411": { id: 411, web_name: "Gillespie", team: "NEW", element_types: "GKP" },
  "412": { id: 412, web_name: "Gordon", team: "NEW", element_types: "MID" },
  "413": { id: 413, web_name: "Hayden", team: "NEW", element_types: "MID" },
  "414": { id: 414, web_name: "Hendrick", team: "NEW", element_types: "MID" },
  "415": { id: 415, web_name: "Isak", team: "NEW", element_types: "FWD" },
  "416": { id: 416, web_name: "Joelinton", team: "NEW", element_types: "MID" },
  "417": { id: 417, web_name: "Krafth", team: "NEW", element_types: "DEF" },
  "418": { id: 418, web_name: "Kuol", team: "NEW", element_types: "MID" },
  "419": { id: 419, web_name: "Lascelles", team: "NEW", element_types: "DEF" },
  "420": { id: 420, web_name: "J.Lewis", team: "NEW", element_types: "DEF" },
  "421": { id: 421, web_name: "Longstaff", team: "NEW", element_types: "MID" },
  "422": { id: 422, web_name: "Manquillo", team: "NEW", element_types: "DEF" },
  "423": { id: 423, web_name: "J.Murphy", team: "NEW", element_types: "MID" },
  "424": { id: 424, web_name: "Pope", team: "NEW", element_types: "GKP" },
  "425": { id: 425, web_name: "Ritchie", team: "NEW", element_types: "MID" },
  "426": {
    id: 426,
    web_name: "Saint-Maximin",
    team: "NEW",
    element_types: "MID",
  },
  "427": { id: 427, web_name: "Schär", team: "NEW", element_types: "DEF" },
  "428": { id: 428, web_name: "Targett", team: "NEW", element_types: "DEF" },
  "429": { id: 429, web_name: "Tonali", team: "NEW", element_types: "MID" },
  "430": { id: 430, web_name: "Trippier", team: "NEW", element_types: "DEF" },
  "431": { id: 431, web_name: "Watts", team: "NEW", element_types: "DEF" },
  "432": { id: 432, web_name: "Willock", team: "NEW", element_types: "MID" },
  "433": { id: 433, web_name: "Wilson", team: "NEW", element_types: "FWD" },
  "434": { id: 434, web_name: "B.Aguilera", team: "NFO", element_types: "MID" },
  "435": { id: 435, web_name: "Arter", team: "NFO", element_types: "MID" },
  "436": { id: 436, web_name: "Aurier", team: "NFO", element_types: "DEF" },
  "437": { id: 437, web_name: "Awoniyi", team: "NFO", element_types: "FWD" },
  "438": { id: 438, web_name: "Biancone", team: "NFO", element_types: "DEF" },
  "439": { id: 439, web_name: "Boly", team: "NFO", element_types: "DEF" },
  "440": { id: 440, web_name: "Bowler", team: "NFO", element_types: "MID" },
  "441": { id: 441, web_name: "Cook", team: "NFO", element_types: "DEF" },
  "442": { id: 442, web_name: "Danilo", team: "NFO", element_types: "MID" },
  "443": { id: 443, web_name: "Dennis", team: "NFO", element_types: "FWD" },
  "444": { id: 444, web_name: "Dräger", team: "NFO", element_types: "DEF" },
  "445": { id: 445, web_name: "Felipe", team: "NFO", element_types: "DEF" },
  "446": { id: 446, web_name: "Freuler", team: "NFO", element_types: "MID" },
  "447": {
    id: 447,
    web_name: "Gibbs-White",
    team: "NFO",
    element_types: "MID",
  },
  "448": { id: 448, web_name: "Hennessey", team: "NFO", element_types: "GKP" },
  "449": { id: 449, web_name: "Horvath", team: "NFO", element_types: "GKP" },
  "450": { id: 450, web_name: "Johnson", team: "TOT", element_types: "MID" },
  "451": { id: 451, web_name: "Kouyaté", team: "NFO", element_types: "MID" },
  "452": { id: 452, web_name: "Laryea", team: "NFO", element_types: "DEF" },
  "453": { id: 453, web_name: "Mangala", team: "NFO", element_types: "MID" },
  "454": { id: 454, web_name: "Mbe Soh", team: "NFO", element_types: "DEF" },
  "455": { id: 455, web_name: "McKenna", team: "NFO", element_types: "DEF" },
  "456": { id: 456, web_name: "Mighten", team: "NFO", element_types: "MID" },
  "457": { id: 457, web_name: "Niakhaté", team: "NFO", element_types: "DEF" },
  "458": { id: 458, web_name: "O'Brien", team: "NFO", element_types: "MID" },
  "459": { id: 459, web_name: "Ojeda", team: "NFO", element_types: "MID" },
  "460": { id: 460, web_name: "Panzo", team: "NFO", element_types: "DEF" },
  "461": { id: 461, web_name: "O.Richards", team: "NFO", element_types: "DEF" },
  "462": { id: 462, web_name: "G.Scarpa", team: "NFO", element_types: "MID" },
  "463": { id: 463, web_name: "J.Shelvey", team: "NFO", element_types: "MID" },
  "464": { id: 464, web_name: "Surridge", team: "NFO", element_types: "FWD" },
  "465": { id: 465, web_name: "Toffolo", team: "NFO", element_types: "DEF" },
  "466": { id: 466, web_name: "Ui-jo", team: "NFO", element_types: "FWD" },
  "467": { id: 467, web_name: "Williams", team: "NFO", element_types: "DEF" },
  "468": { id: 468, web_name: "Wood", team: "NFO", element_types: "FWD" },
  "469": { id: 469, web_name: "Worrall", team: "NFO", element_types: "DEF" },
  "470": { id: 470, web_name: "Yates", team: "NFO", element_types: "MID" },
  "471": {
    id: 471,
    web_name: "Ahmedhodžić",
    team: "SHU",
    element_types: "DEF",
  },
  "472": { id: 472, web_name: "Amissah", team: "SHU", element_types: "GKP" },
  "473": { id: 473, web_name: "Baldock", team: "SHU", element_types: "DEF" },
  "474": { id: 474, web_name: "Basham", team: "SHU", element_types: "DEF" },
  "475": { id: 475, web_name: "Berge", team: "BUR", element_types: "MID" },
  "476": { id: 476, web_name: "Bogle", team: "SHU", element_types: "DEF" },
  "477": { id: 477, web_name: "Brewster", team: "SHU", element_types: "FWD" },
  "478": { id: 478, web_name: "Coulibaly", team: "SHU", element_types: "MID" },
  "479": { id: 479, web_name: "A.Davies", team: "SHU", element_types: "GKP" },
  "480": { id: 480, web_name: "Egan", team: "SHU", element_types: "DEF" },
  "481": { id: 481, web_name: "Fleck", team: "SHU", element_types: "MID" },
  "482": {
    id: 482,
    web_name: "Foderingham",
    team: "SHU",
    element_types: "GKP",
  },
  "483": { id: 483, web_name: "Jebbison", team: "SHU", element_types: "FWD" },
  "484": { id: 484, web_name: "Lowe", team: "SHU", element_types: "DEF" },
  "485": { id: 485, web_name: "McBurnie", team: "SHU", element_types: "FWD" },
  "486": { id: 486, web_name: "Ndiaye", team: "SHU", element_types: "FWD" },
  "487": {
    id: 487,
    web_name: "Norrington-Davies",
    team: "SHU",
    element_types: "DEF",
  },
  "488": { id: 488, web_name: "Norwood", team: "SHU", element_types: "MID" },
  "489": { id: 489, web_name: "Osborn", team: "SHU", element_types: "MID" },
  "490": { id: 490, web_name: "Osula", team: "SHU", element_types: "FWD" },
  "491": { id: 491, web_name: "Austin", team: "TOT", element_types: "GKP" },
  "492": { id: 492, web_name: "Bentancur", team: "TOT", element_types: "MID" },
  "493": { id: 493, web_name: "Bissouma", team: "TOT", element_types: "MID" },
  "494": { id: 494, web_name: "Bryan", team: "TOT", element_types: "MID" },
  "495": { id: 495, web_name: "Davies", team: "TOT", element_types: "DEF" },
  "496": { id: 496, web_name: "Dier", team: "TOT", element_types: "DEF" },
  "497": { id: 497, web_name: "E.Royal", team: "TOT", element_types: "DEF" },
  "498": { id: 498, web_name: "Forster", team: "TOT", element_types: "GKP" },
  "499": { id: 499, web_name: "Højbjerg", team: "TOT", element_types: "MID" },
  "500": { id: 500, web_name: "Kane", team: "TOT", element_types: "FWD" },
  "501": { id: 501, web_name: "Kulusevski", team: "TOT", element_types: "MID" },
  "502": { id: 502, web_name: "Lloris", team: "TOT", element_types: "GKP" },
  "503": { id: 503, web_name: "Lo Celso", team: "TOT", element_types: "MID" },
  "504": { id: 504, web_name: "Maddison", team: "TOT", element_types: "MID" },
  "505": { id: 505, web_name: "Ndombele", team: "TOT", element_types: "MID" },
  "506": {
    id: 506,
    web_name: "Pedro Porro",
    team: "TOT",
    element_types: "DEF",
  },
  "507": { id: 507, web_name: "Perišić", team: "TOT", element_types: "DEF" },
  "508": { id: 508, web_name: "Reguilón", team: "TOT", element_types: "DEF" },
  "509": {
    id: 509,
    web_name: "Richarlison",
    team: "TOT",
    element_types: "MID",
  },
  "510": { id: 510, web_name: "Rodon", team: "TOT", element_types: "DEF" },
  "511": { id: 511, web_name: "Romero", team: "TOT", element_types: "DEF" },
  "512": { id: 512, web_name: "Sánchez", team: "TOT", element_types: "DEF" },
  "513": { id: 513, web_name: "Sarr", team: "TOT", element_types: "MID" },
  "514": { id: 514, web_name: "Sessegnon", team: "TOT", element_types: "DEF" },
  "515": { id: 515, web_name: "Skipp", team: "TOT", element_types: "MID" },
  "516": { id: 516, web_name: "Son", team: "TOT", element_types: "MID" },
  "517": { id: 517, web_name: "Spence", team: "TOT", element_types: "DEF" },
  "518": { id: 518, web_name: "Tanganga", team: "TOT", element_types: "DEF" },
  "519": { id: 519, web_name: "Udogie", team: "TOT", element_types: "DEF" },
  "520": { id: 520, web_name: "Vicario", team: "TOT", element_types: "GKP" },
  "521": { id: 521, web_name: "Whiteman", team: "TOT", element_types: "GKP" },
  "522": { id: 522, web_name: "N.Aguerd", team: "WHU", element_types: "DEF" },
  "523": { id: 523, web_name: "Antonio", team: "WHU", element_types: "FWD" },
  "524": { id: 524, web_name: "Areola", team: "WHU", element_types: "GKP" },
  "525": { id: 525, web_name: "Benrahma", team: "WHU", element_types: "MID" },
  "526": { id: 526, web_name: "Bowen", team: "WHU", element_types: "MID" },
  "527": { id: 527, web_name: "Cornet", team: "WHU", element_types: "MID" },
  "528": { id: 528, web_name: "Coufal", team: "WHU", element_types: "DEF" },
  "529": { id: 529, web_name: "Coventry", team: "WHU", element_types: "MID" },
  "530": { id: 530, web_name: "Cresswell", team: "WHU", element_types: "DEF" },
  "531": { id: 531, web_name: "Downes", team: "WHU", element_types: "MID" },
  "532": { id: 532, web_name: "Emerson", team: "WHU", element_types: "DEF" },
  "533": { id: 533, web_name: "Fabianski", team: "WHU", element_types: "GKP" },
  "534": { id: 534, web_name: "P.Fornals", team: "WHU", element_types: "MID" },
  "535": { id: 535, web_name: "Ings", team: "WHU", element_types: "FWD" },
  "536": { id: 536, web_name: "Johnson", team: "WHU", element_types: "DEF" },
  "537": { id: 537, web_name: "Kehrer", team: "WHU", element_types: "DEF" },
  "538": { id: 538, web_name: "Mubama", team: "WHU", element_types: "FWD" },
  "539": { id: 539, web_name: "L.Paquetá", team: "WHU", element_types: "MID" },
  "540": { id: 540, web_name: "Rice", team: "ARS", element_types: "MID" },
  "541": { id: 541, web_name: "Scamacca", team: "WHU", element_types: "FWD" },
  "542": { id: 542, web_name: "Souček", team: "WHU", element_types: "MID" },
  "543": { id: 543, web_name: "Vlašić", team: "WHU", element_types: "MID" },
  "544": { id: 544, web_name: "Zouma", team: "WHU", element_types: "DEF" },
  "545": { id: 545, web_name: "Aït-Nouri", team: "WOL", element_types: "DEF" },
  "546": { id: 546, web_name: "Bentley", team: "WOL", element_types: "GKP" },
  "547": { id: 547, web_name: "Bolla", team: "WOL", element_types: "DEF" },
  "548": { id: 548, web_name: "H.Bueno", team: "WOL", element_types: "DEF" },
  "549": { id: 549, web_name: "Chiquinho", team: "WOL", element_types: "MID" },
  "550": { id: 550, web_name: "Cundle", team: "WOL", element_types: "MID" },
  "551": { id: 551, web_name: "Dawson", team: "WOL", element_types: "DEF" },
  "552": {
    id: 552,
    web_name: "Fábio Silva",
    team: "WOL",
    element_types: "FWD",
  },
  "553": { id: 553, web_name: "Giles", team: "LUT", element_types: "DEF" },
  "554": { id: 554, web_name: "Guedes", team: "WOL", element_types: "MID" },
  "555": { id: 555, web_name: "Hodge", team: "WOL", element_types: "MID" },
  "556": { id: 556, web_name: "Hoever", team: "WOL", element_types: "DEF" },
  "557": { id: 557, web_name: "Hee Chan", team: "WOL", element_types: "MID" },
  "558": { id: 558, web_name: "Raúl", team: "FUL", element_types: "FWD" },
  "559": { id: 559, web_name: "João Gomes", team: "WOL", element_types: "MID" },
  "560": { id: 560, web_name: "J.Otto", team: "WOL", element_types: "DEF" },
  "561": { id: 561, web_name: "Jordão", team: "WOL", element_types: "MID" },
  "562": { id: 562, web_name: "Kalajdžić", team: "WOL", element_types: "FWD" },
  "563": { id: 563, web_name: "Kilman", team: "WOL", element_types: "DEF" },
  "564": { id: 564, web_name: "King", team: "WOL", element_types: "GKP" },
  "565": { id: 565, web_name: "Lemina", team: "WOL", element_types: "MID" },
  "566": { id: 566, web_name: "Matheus N.", team: "MCI", element_types: "MID" },
  "567": { id: 567, web_name: "Neto", team: "WOL", element_types: "MID" },
  "568": { id: 568, web_name: "Podence", team: "WOL", element_types: "MID" },
  "569": { id: 569, web_name: "José Sá", team: "WOL", element_types: "GKP" },
  "570": { id: 570, web_name: "Sarabia", team: "WOL", element_types: "MID" },
  "571": { id: 571, web_name: "Šarkić", team: "WOL", element_types: "GKP" },
  "572": { id: 572, web_name: "N.Semedo", team: "WOL", element_types: "DEF" },
  "573": { id: 573, web_name: "Toti", team: "WOL", element_types: "DEF" },
  "574": {
    id: 574,
    web_name: "Boubacar Traore",
    team: "WOL",
    element_types: "MID",
  },
  "575": { id: 575, web_name: "Lockyer", team: "LUT", element_types: "DEF" },
  "576": { id: 576, web_name: "Robinson", team: "SHU", element_types: "DEF" },
  "577": { id: 577, web_name: "Ogbonna", team: "WHU", element_types: "DEF" },
  "578": { id: 578, web_name: "Nelson", team: "ARS", element_types: "MID" },
  "579": { id: 579, web_name: "Lonergan", team: "EVE", element_types: "GKP" },
  "580": { id: 580, web_name: "Karius", team: "NEW", element_types: "GKP" },
  "581": { id: 581, web_name: "Dummett", team: "NEW", element_types: "DEF" },
  "582": { id: 582, web_name: "Mpanzu", team: "LUT", element_types: "MID" },
  "583": { id: 583, web_name: "Solomon", team: "TOT", element_types: "MID" },
  "584": { id: 584, web_name: "Pau", team: "AVL", element_types: "DEF" },
  "585": { id: 585, web_name: "J.Timber", team: "ARS", element_types: "DEF" },
  "586": { id: 586, web_name: "Chong", team: "LUT", element_types: "MID" },
  "587": { id: 587, web_name: "Slimane", team: "SHU", element_types: "MID" },
  "588": { id: 588, web_name: "Young", team: "EVE", element_types: "DEF" },
  "589": { id: 589, web_name: "Ângelo", team: "CHE", element_types: "MID" },
  "590": { id: 590, web_name: "Cunha", team: "WOL", element_types: "FWD" },
  "591": { id: 591, web_name: "Willian", team: "FUL", element_types: "MID" },
  "592": { id: 592, web_name: "Larouci", team: "SHU", element_types: "DEF" },
  "593": { id: 593, web_name: "T.Bénie", team: "SHU", element_types: "FWD" },
  "594": { id: 594, web_name: "Amdouni", team: "BUR", element_types: "FWD" },
  "595": { id: 595, web_name: "Kerkez", team: "BOU", element_types: "DEF" },
  "596": { id: 596, web_name: "Trafford", team: "BUR", element_types: "GKP" },
  "597": { id: 597, web_name: "Onana", team: "MUN", element_types: "GKP" },
  "598": { id: 598, web_name: "Doherty", team: "WOL", element_types: "DEF" },
  "599": { id: 599, web_name: "Diaby", team: "AVL", element_types: "MID" },
  "600": { id: 600, web_name: "Redmond", team: "BUR", element_types: "MID" },
  "601": { id: 601, web_name: "Danjuma", team: "EVE", element_types: "MID" },
  "602": { id: 602, web_name: "Kaboré", team: "LUT", element_types: "DEF" },
  "603": { id: 603, web_name: "Barnes", team: "NEW", element_types: "MID" },
  "604": { id: 604, web_name: "Aina", team: "NFO", element_types: "DEF" },
  "605": { id: 605, web_name: "Koleosho", team: "BUR", element_types: "MID" },
  "606": { id: 606, web_name: "Igor", team: "BHA", element_types: "DEF" },
  "607": { id: 607, web_name: "Radu", team: "BOU", element_types: "GKP" },
  "608": {
    id: 608,
    web_name: "Bruun Larsen",
    team: "BUR",
    element_types: "MID",
  },
  "609": { id: 609, web_name: "Maatsen", team: "CHE", element_types: "MID" },
  "610": { id: 610, web_name: "Bassey", team: "FUL", element_types: "DEF" },
  "611": { id: 611, web_name: "Disasi", team: "CHE", element_types: "DEF" },
  "613": { id: 613, web_name: "Ugochukwu", team: "CHE", element_types: "MID" },
  "614": { id: 614, web_name: "Kaminski", team: "LUT", element_types: "GKP" },
  "615": {
    id: 615,
    web_name: "Matheus França",
    team: "CRY",
    element_types: "MID",
  },
  "616": { id: 616, web_name: "Gvardiol", team: "MCI", element_types: "DEF" },
  "617": { id: 617, web_name: "Højlund", team: "MUN", element_types: "FWD" },
  "618": { id: 618, web_name: "Kellyman", team: "AVL", element_types: "MID" },
  "619": { id: 619, web_name: "Greenwood", team: "BOU", element_types: "DEF" },
  "620": { id: 620, web_name: "Olakigbe", team: "BRE", element_types: "MID" },
  "621": {
    id: 621,
    web_name: "Hinshelwood",
    team: "BHA",
    element_types: "MID",
  },
  "622": { id: 622, web_name: "Dodgson", team: "BUR", element_types: "DEF" },
  "623": { id: 623, web_name: "Burstow", team: "CHE", element_types: "FWD" },
  "624": { id: 624, web_name: "Dobbin", team: "EVE", element_types: "MID" },
  "625": {
    id: 625,
    web_name: "De Fougerolles",
    team: "FUL",
    element_types: "DEF",
  },
  "626": { id: 626, web_name: "Quansah", team: "LIV", element_types: "DEF" },
  "627": { id: 627, web_name: "Clark", team: "LIV", element_types: "MID" },
  "628": { id: 628, web_name: "Doak", team: "LIV", element_types: "MID" },
  "629": { id: 629, web_name: "McConnell", team: "LIV", element_types: "MID" },
  "630": { id: 630, web_name: "Barkley", team: "LUT", element_types: "MID" },
  "631": { id: 631, web_name: "Brown", team: "LUT", element_types: "FWD" },
  "632": { id: 632, web_name: "Forson", team: "MUN", element_types: "MID" },
  "633": { id: 633, web_name: "Livramento", team: "NEW", element_types: "DEF" },
  "634": { id: 634, web_name: "A.Murphy", team: "NEW", element_types: "DEF" },
  "635": { id: 635, web_name: "Miley", team: "NEW", element_types: "MID" },
  "636": { id: 636, web_name: "G.Shelvey", team: "NFO", element_types: "GKP" },
  "637": { id: 637, web_name: "Powell", team: "NFO", element_types: "DEF" },
  "638": { id: 638, web_name: "Vini Souza", team: "SHU", element_types: "MID" },
  "639": { id: 639, web_name: "Van de Ven", team: "TOT", element_types: "DEF" },
  "640": { id: 640, web_name: "Scarlett", team: "TOT", element_types: "FWD" },
  "641": { id: 641, web_name: "Veliz", team: "TOT", element_types: "FWD" },
  "642": { id: 642, web_name: "Álvarez", team: "WHU", element_types: "MID" },
  "643": { id: 643, web_name: "Aarons", team: "BOU", element_types: "DEF" },
  "644": { id: 644, web_name: "Scott", team: "BOU", element_types: "MID" },
  "645": {
    id: 645,
    web_name: "Y. Chermiti",
    team: "EVE",
    element_types: "FWD",
  },
  "646": { id: 646, web_name: "Hein", team: "ARS", element_types: "GKP" },
  "647": { id: 647, web_name: "Anang", team: "WHU", element_types: "GKP" },
  "648": {
    id: 648,
    web_name: "Francis-Clarke",
    team: "LUT",
    element_types: "DEF",
  },
  "649": { id: 649, web_name: "Cannon", team: "EVE", element_types: "FWD" },
  "650": { id: 650, web_name: "Onyango", team: "EVE", element_types: "MID" },
  "651": { id: 651, web_name: "Stansfield", team: "FUL", element_types: "FWD" },
  "652": {
    id: 652,
    web_name: "Dibley-Dias",
    team: "FUL",
    element_types: "MID",
  },
  "653": { id: 653, web_name: "Seriki", team: "SHU", element_types: "DEF" },
  "654": { id: 654, web_name: "Marsh", team: "SHU", element_types: "FWD" },
  "655": { id: 655, web_name: "Brooks", team: "SHU", element_types: "MID" },
  "656": { id: 656, web_name: "Hackford", team: "SHU", element_types: "FWD" },
  "657": { id: 657, web_name: "Rak-Sakyi", team: "CRY", element_types: "MID" },
  "658": { id: 658, web_name: "Gordon", team: "CRY", element_types: "FWD" },
  "659": { id: 659, web_name: "Bergström", team: "CHE", element_types: "GKP" },
  "660": { id: 660, web_name: "Odobert", team: "BUR", element_types: "MID" },
  "661": { id: 661, web_name: "Harrison", team: "EVE", element_types: "MID" },
  "662": { id: 662, web_name: "Adama", team: "FUL", element_types: "MID" },
  "663": { id: 663, web_name: "Hamer", team: "SHU", element_types: "MID" },
  "664": {
    id: 664,
    web_name: "Ward-Prowse",
    team: "WHU",
    element_types: "MID",
  },
  "665": { id: 665, web_name: "Krul", team: "LUT", element_types: "GKP" },
  "666": { id: 666, web_name: "T.Davies", team: "SHU", element_types: "MID" },
  "667": { id: 667, web_name: "Lavia", team: "CHE", element_types: "MID" },
  "668": { id: 668, web_name: "Endo", team: "LIV", element_types: "MID" },
  "669": { id: 669, web_name: "Vítek", team: "MUN", element_types: "GKP" },
  "670": { id: 670, web_name: "Marschall", team: "AVL", element_types: "GKP" },
  "671": { id: 671, web_name: "Humphreys", team: "CHE", element_types: "DEF" },
  "672": { id: 672, web_name: "Zaniolo", team: "AVL", element_types: "MID" },
  "673": { id: 673, web_name: "Adams", team: "BOU", element_types: "MID" },
  "674": { id: 674, web_name: "Delcroix", team: "BUR", element_types: "DEF" },
  "675": { id: 675, web_name: "A.Ramsey", team: "BUR", element_types: "MID" },
  "676": { id: 676, web_name: "Mavropanos", team: "WHU", element_types: "DEF" },
  "677": { id: 677, web_name: "Deivid", team: "CHE", element_types: "FWD" },
  "678": { id: 678, web_name: "Doku", team: "MCI", element_types: "MID" },
  "679": { id: 679, web_name: "G.Montiel", team: "NFO", element_types: "DEF" },
  "680": { id: 680, web_name: "Beach", team: "CHE", element_types: "GKP" },
  "681": {
    id: 681,
    web_name: "Diego Moreira",
    team: "CHE",
    element_types: "MID",
  },
  "682": { id: 682, web_name: "Johnson", team: "LUT", element_types: "DEF" },
  "683": { id: 683, web_name: "Harris", team: "FUL", element_types: "MID" },
  "684": { id: 684, web_name: "Brierley", team: "BRE", element_types: "MID" },
  "685": { id: 685, web_name: "Gore", team: "MUN", element_types: "MID" },
  "686": { id: 686, web_name: "Zych", team: "AVL", element_types: "GKP" },
  "687": { id: 687, web_name: "Petrović", team: "CHE", element_types: "GKP" },
  "688": { id: 688, web_name: "Castagne", team: "FUL", element_types: "DEF" },
  "689": { id: 689, web_name: "Kudus", team: "WHU", element_types: "MID" },
  "690": { id: 690, web_name: "Baleba", team: "BHA", element_types: "MID" },
  "691": { id: 691, web_name: "Beto", team: "EVE", element_types: "FWD" },
  "692": { id: 692, web_name: "Benda", team: "FUL", element_types: "GKP" },
  "693": { id: 693, web_name: "Thomas", team: "SHU", element_types: "DEF" },
  "694": { id: 694, web_name: "Massengo", team: "BUR", element_types: "MID" },
  "695": { id: 695, web_name: "Altay", team: "MUN", element_types: "GKP" },
  "696": { id: 696, web_name: "Murillo", team: "NFO", element_types: "DEF" },
  "697": { id: 697, web_name: "S.Bueno", team: "WOL", element_types: "DEF" },
  "698": { id: 698, web_name: "González", team: "WOL", element_types: "MID" },
  "699": { id: 699, web_name: "Lenglet", team: "AVL", element_types: "DEF" },
  "700": { id: 700, web_name: "Ansu Fati", team: "BHA", element_types: "MID" },
  "701": { id: 701, web_name: "Ghoddos", team: "BRE", element_types: "MID" },
  "702": { id: 702, web_name: "Phillips", team: "TOT", element_types: "DEF" },
  "703": { id: 703, web_name: "Evans", team: "MUN", element_types: "DEF" },
  "704": { id: 704, web_name: "Fraser", team: "WOL", element_types: "FWD" },
  "705": { id: 705, web_name: "Sinisterra", team: "BOU", element_types: "MID" },
  "706": { id: 706, web_name: "M.Trésor", team: "BUR", element_types: "MID" },
  "707": {
    id: 707,
    web_name: "Ballo-Touré",
    team: "FUL",
    element_types: "DEF",
  },
  "708": {
    id: 708,
    web_name: "Gravenberch",
    team: "LIV",
    element_types: "MID",
  },
  "709": { id: 709, web_name: "Amrabat", team: "MUN", element_types: "MID" },
  "710": { id: 710, web_name: "Odysseas", team: "NFO", element_types: "GKP" },
  "711": {
    id: 711,
    web_name: "Omobamidele",
    team: "NFO",
    element_types: "DEF",
  },
  "712": { id: 712, web_name: "Dominguez", team: "NFO", element_types: "MID" },
  "713": { id: 713, web_name: "Sangaré", team: "NFO", element_types: "MID" },
  "714": { id: 714, web_name: "Origi", team: "NFO", element_types: "FWD" },
  "715": { id: 715, web_name: "Bellegarde", team: "WOL", element_types: "MID" },
  "716": { id: 716, web_name: "Gilchrist", team: "CHE", element_types: "DEF" },
  "717": { id: 717, web_name: "Stutter", team: "CHE", element_types: "FWD" },
  "718": { id: 718, web_name: "Matos", team: "CHE", element_types: "MID" },
  "719": { id: 719, web_name: "Hunt", team: "EVE", element_types: "MID" },
  "720": {
    id: 720,
    web_name: "Ola-Adebomi",
    team: "CRY",
    element_types: "FWD",
  },
  "721": { id: 721, web_name: "Ozoh", team: "CRY", element_types: "MID" },
  "722": { id: 722, web_name: "Donley", team: "TOT", element_types: "FWD" },
  "723": { id: 723, web_name: "Brooking", team: "CHE", element_types: "DEF" },
  "724": { id: 724, web_name: "Raymond", team: "CRY", element_types: "MID" },
  "725": { id: 725, web_name: "Kim Ji-Soo", team: "BRE", element_types: "DEF" },
  "726": { id: 726, web_name: "Chambers", team: "LIV", element_types: "DEF" },
  "727": { id: 727, web_name: "Townsend", team: "LUT", element_types: "MID" },
  "728": { id: 728, web_name: "Scanlon", team: "LIV", element_types: "DEF" },
  "729": { id: 729, web_name: "Luker", team: "LUT", element_types: "MID" },
  "730": { id: 730, web_name: "Oné", team: "SHU", element_types: "MID" },
  "731": { id: 731, web_name: "Buyabu", team: "SHU", element_types: "DEF" },
  "732": { id: 732, web_name: "Tanton", team: "FUL", element_types: "DEF" },
  "733": { id: 733, web_name: "Adedokun", team: "BRE", element_types: "DEF" },
  "734": { id: 734, web_name: "Nelson", team: "LUT", element_types: "MID" },
  "735": { id: 735, web_name: "Sagoe", team: "ARS", element_types: "MID" },
  "736": { id: 736, web_name: "Walters", team: "ARS", element_types: "DEF" },
  "737": { id: 737, web_name: "Ibrahim", team: "ARS", element_types: "MID" },
  "738": { id: 738, web_name: "Diallo", team: "NEW", element_types: "MID" },
  "739": { id: 739, web_name: "Parkinson", team: "NEW", element_types: "FWD" },
  "740": { id: 740, web_name: "Dorrington", team: "TOT", element_types: "DEF" },
  "741": { id: 741, web_name: "O’Mahony", team: "BHA", element_types: "FWD" },
  "742": {
    id: 742,
    web_name: "Baker-Boaitey",
    team: "BHA",
    element_types: "MID",
  },
  "743": { id: 743, web_name: "Nyoni", team: "LIV", element_types: "MID" },
  "744": {
    id: 744,
    web_name: "Peart-Harris",
    team: "BRE",
    element_types: "MID",
  },
  "745": { id: 745, web_name: "Ndiweni", team: "NEW", element_types: "FWD" },
  "746": { id: 746, web_name: "Jackson", team: "BHA", element_types: "DEF" },
  "747": { id: 747, web_name: "Duffus", team: "BHA", element_types: "MID" },
  "748": { id: 748, web_name: "Hugill", team: "MUN", element_types: "FWD" },
  "749": {
    id: 749,
    web_name: "Whittingham",
    team: "WOL",
    element_types: "MID",
  },
  "750": { id: 750, web_name: "Chirewa", team: "WOL", element_types: "MID" },
  "751": { id: 751, web_name: "Hubner", team: "WOL", element_types: "DEF" },
  "752": { id: 752, web_name: "Angelini", team: "BRE", element_types: "GKP" },
  "753": { id: 753, web_name: "Kavanagh", team: "BHA", element_types: "DEF" },
  "754": {
    id: 754,
    web_name: "Yago Santiago",
    team: "TOT",
    element_types: "MID",
  },
  "755": { id: 755, web_name: "Barrington", team: "BHA", element_types: "MID" },
  "756": { id: 756, web_name: "Pitaluga", team: "LIV", element_types: "GKP" },
  "757": { id: 757, web_name: "Bradley", team: "LIV", element_types: "DEF" },
  "758": { id: 758, web_name: "Castledine", team: "CHE", element_types: "MID" },
  "759": { id: 759, web_name: "Peck", team: "SHU", element_types: "MID" },
  "760": { id: 760, web_name: "Metcalfe", team: "EVE", element_types: "MID" },
  "761": { id: 761, web_name: "Campbell", team: "EVE", element_types: "DEF" },
  "762": { id: 762, web_name: "Susoho", team: "MCI", element_types: "MID" },
  "763": { id: 763, web_name: "Adaramola", team: "CRY", element_types: "DEF" },
  "764": {
    id: 764,
    web_name: "Lewis-Skelly",
    team: "ARS",
    element_types: "MID",
  },
  "765": { id: 765, web_name: "Proctor", team: "AVL", element_types: "GKP" },
  "766": { id: 766, web_name: "Kambwala", team: "MUN", element_types: "DEF" },
  "767": { id: 767, web_name: "O'Reilly", team: "AVL", element_types: "MID" },
  "768": { id: 768, web_name: "Bennett", team: "MUN", element_types: "DEF" },
  "769": { id: 769, web_name: "Hesketh", team: "WOL", element_types: "MID" },
  "770": { id: 770, web_name: "Barnett", team: "WOL", element_types: "MID" },
  "771": { id: 771, web_name: "Hamilton", team: "MCI", element_types: "MID" },
  "772": { id: 772, web_name: "Nwaneri", team: "ARS", element_types: "MID" },
  "773": { id: 773, web_name: "Orford", team: "WHU", element_types: "MID" },
  "774": { id: 774, web_name: "Casey", team: "WHU", element_types: "DEF" },
  "775": {
    id: 775,
    web_name: "Brereton Díaz",
    team: "SHU",
    element_types: "MID",
  },
  "776": { id: 776, web_name: "Werner", team: "TOT", element_types: "FWD" },
};
export default elements;
