const picks = [
  {
    active_chip: null,
    automatic_subs: [
      { entry: 5524951, element_in: 60, element_out: 346, event: 1 },
    ],
    entry_history: {
      event: 1,
      points: 58,
      total_points: 58,
      rank: 5703138,
      rank_sort: 5821239,
      overall_rank: 5703139,
      percentile_rank: null,
      bank: 0,
      value: 1000,
      event_transfers: 0,
      event_transfers_cost: 0,
      points_on_bench: 3,
    },
    picks: [
      {
        element: 597,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 430,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 51,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 396,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 26,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 304,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 10,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 278,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 263,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 109,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 346,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 43,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: "wildcard",
    automatic_subs: [],
    entry_history: {
      event: 2,
      points: 54,
      total_points: 112,
      rank: 1768008,
      rank_sort: 1815189,
      overall_rank: 3564816,
      percentile_rank: null,
      bank: 18,
      value: 1002,
      event_transfers: 0,
      event_transfers_cost: 0,
      points_on_bench: 11,
    },
    picks: [
      {
        element: 597,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 195,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 131,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 365,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 504,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 429,
        position: 8,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 13,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 263,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 341,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 396,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: "bboost",
    automatic_subs: [],
    entry_history: {
      event: 3,
      points: 51,
      total_points: 163,
      rank: 2332672,
      rank_sort: 2386999,
      overall_rank: 2623790,
      percentile_rank: null,
      bank: 27,
      value: 1009,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 0,
    },
    picks: [
      {
        element: 263,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 195,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 108,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 429,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 396,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 60,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 13,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 11,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 597,
        position: 12,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 365,
        position: 13,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 131,
        position: 14,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 341,
        position: 15,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [],
    entry_history: {
      event: 4,
      points: 68,
      total_points: 231,
      rank: 6719126,
      rank_sort: 6781901,
      overall_rank: 3366447,
      percentile_rank: null,
      bank: 5,
      value: 1013,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 9,
    },
    picks: [
      {
        element: 597,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 195,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 131,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 341,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 108,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 365,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 303,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 396,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 13,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 11,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 263,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [
      { entry: 5524951, element_in: 143, element_out: 131, event: 5 },
    ],
    entry_history: {
      event: 5,
      points: 37,
      total_points: 268,
      rank: 7916370,
      rank_sort: 7981965,
      overall_rank: 4188801,
      percentile_rank: null,
      bank: 9,
      value: 1012,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 12,
    },
    picks: [
      {
        element: 597,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 195,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 341,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 396,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 365,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 108,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 303,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 11,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 524,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 131,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 13,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [],
    entry_history: {
      event: 6,
      points: 57,
      total_points: 325,
      rank: 7776465,
      rank_sort: 7807163,
      overall_rank: 5137533,
      percentile_rank: null,
      bank: 8,
      value: 1007,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 23,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 131,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 341,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 108,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 365,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 396,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 10,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 597,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 303,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 195,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [],
    entry_history: {
      event: 7,
      points: 58,
      total_points: 375,
      rank: 2614265,
      rank_sort: 2620352,
      overall_rank: 4957043,
      percentile_rank: null,
      bank: 0,
      value: 1010,
      event_transfers: 3,
      event_transfers_cost: 8,
      points_on_bench: 3,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 131,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 143,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 396,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 108,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 11,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 597,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 341,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 195,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [
      { entry: 5524951, element_in: 20, element_out: 341, event: 8 },
      { entry: 5524951, element_in: 108, element_out: 19, event: 8 },
    ],
    entry_history: {
      event: 8,
      points: 38,
      total_points: 409,
      rank: 7146965,
      rank_sort: 7184383,
      overall_rank: 5562650,
      percentile_rank: null,
      bank: 2,
      value: 1007,
      event_transfers: 2,
      event_transfers_cost: 4,
      points_on_bench: 2,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 516,
        position: 5,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 108,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 355,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 597,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 341,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 131,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: "freehit",
    automatic_subs: [],
    entry_history: {
      event: 9,
      points: 87,
      total_points: 496,
      rank: 1200228,
      rank_sort: 1246337,
      overall_rank: 4225890,
      percentile_rank: null,
      bank: 2,
      value: 1005,
      event_transfers: 0,
      event_transfers_cost: 0,
      points_on_bench: 4,
    },
    picks: [
      {
        element: 28,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 377,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 506,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 373,
        position: 6,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 567,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 106,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 293,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 524,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 203,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 27,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 52,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: "3xc",
    automatic_subs: [
      { entry: 5524951, element_in: 108, element_out: 519, event: 10 },
    ],
    entry_history: {
      event: 10,
      points: 73,
      total_points: 569,
      rank: 3096816,
      rank_sort: 3137567,
      overall_rank: 3822845,
      percentile_rank: null,
      bank: 5,
      value: 1005,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 4,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 108,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 516,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 9,
        multiplier: 3,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 355,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 597,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 131,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [],
    entry_history: {
      event: 11,
      points: 26,
      total_points: 595,
      rank: 7560794,
      rank_sort: 7632966,
      overall_rank: 4168683,
      percentile_rank: null,
      bank: 17,
      value: 1007,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 12,
    },
    picks: [
      {
        element: 597,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 516,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 225,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 11,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 524,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 131,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [],
    entry_history: {
      event: 12,
      points: 68,
      total_points: 663,
      rank: 4239514,
      rank_sort: 4280878,
      overall_rank: 3982318,
      percentile_rank: null,
      bank: 22,
      value: 1009,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 19,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 234,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 430,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 516,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 10,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 597,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [],
    entry_history: {
      event: 13,
      points: 48,
      total_points: 707,
      rank: 4370738,
      rank_sort: 4411893,
      overall_rank: 4129123,
      percentile_rank: null,
      bank: 9,
      value: 1010,
      event_transfers: 2,
      event_transfers_cost: 4,
      points_on_bench: 18,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 234,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 8,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 225,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 597,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 311,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 143,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [],
    entry_history: {
      event: 14,
      points: 43,
      total_points: 750,
      rank: 8823861,
      rank_sort: 8841478,
      overall_rank: 4795537,
      percentile_rank: null,
      bank: 4,
      value: 1014,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 14,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 311,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 7,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 216,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 597,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 234,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [
      { entry: 5524951, element_in: 519, element_out: 311, event: 15 },
    ],
    entry_history: {
      event: 15,
      points: 32,
      total_points: 782,
      rank: 6625371,
      rank_sort: 6698163,
      overall_rank: 4948647,
      percentile_rank: null,
      bank: 9,
      value: 1015,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 10,
    },
    picks: [
      {
        element: 597,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 419,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 20,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 6,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 216,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 524,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 311,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [
      { entry: 5524951, element_in: 5, element_out: 355, event: 16 },
    ],
    entry_history: {
      event: 16,
      points: 50,
      total_points: 832,
      rank: 2939465,
      rank_sort: 2975838,
      overall_rank: 4446429,
      percentile_rank: null,
      bank: 17,
      value: 1014,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 0,
    },
    picks: [
      {
        element: 597,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 311,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 283,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 216,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 11,
        multiplier: 2,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 524,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 13,
        multiplier: 0,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 419,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [],
    entry_history: {
      event: 17,
      points: 52,
      total_points: 884,
      rank: 3206715,
      rank_sort: 3242864,
      overall_rank: 4094018,
      percentile_rank: null,
      bank: 21,
      value: 1015,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 1,
    },
    picks: [
      {
        element: 263,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 311,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 419,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 216,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 10,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 524,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 283,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [],
    entry_history: {
      event: 18,
      points: 42,
      total_points: 926,
      rank: 3487221,
      rank_sort: 3529441,
      overall_rank: 3944870,
      percentile_rank: null,
      bank: 3,
      value: 1013,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 2,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 311,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 283,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 419,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 216,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 60,
        position: 11,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 263,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 225,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [
      { entry: 5524951, element_in: 664, element_out: 355, event: 19 },
    ],
    entry_history: {
      event: 19,
      points: 42,
      total_points: 964,
      rank: 3720492,
      rank_sort: 3750791,
      overall_rank: 3974880,
      percentile_rank: null,
      bank: 12,
      value: 1012,
      event_transfers: 2,
      event_transfers_cost: 4,
      points_on_bench: 10,
    },
    picks: [
      {
        element: 263,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 83,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 283,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 6,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 314,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 524,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 355,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 216,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 419,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [
      { entry: 5524951, element_in: 664, element_out: 216, event: 20 },
    ],
    entry_history: {
      event: 20,
      points: 76,
      total_points: 1040,
      rank: 2316942,
      rank_sort: 2349769,
      overall_rank: 3547296,
      percentile_rank: null,
      bank: 83,
      value: 1014,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 3,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 283,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 557,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 343,
        position: 10,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 314,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 263,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 216,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 83,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 419,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [
      { entry: 5524951, element_in: 283, element_out: 419, event: 21 },
    ],
    entry_history: {
      event: 21,
      points: 58,
      total_points: 1098,
      rank: 2486980,
      rank_sort: 2506871,
      overall_rank: 3208481,
      percentile_rank: 25,
      bank: 73,
      value: 1014,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 3,
    },
    picks: [
      {
        element: 263,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 283,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 216,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 134,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 19,
        position: 8,
        multiplier: 2,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 343,
        position: 10,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 314,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 524,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 419,
        position: 13,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 83,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
  {
    active_chip: null,
    automatic_subs: [
      { entry: 5524951, element_in: 134, element_out: 344, event: 22 },
    ],
    entry_history: {
      event: 22,
      points: 87,
      total_points: 1185,
      rank: 29595,
      rank_sort: 31234,
      overall_rank: 2233361,
      percentile_rank: 1,
      bank: 97,
      value: 1011,
      event_transfers: 1,
      event_transfers_cost: 0,
      points_on_bench: 10,
    },
    picks: [
      {
        element: 524,
        position: 1,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 83,
        position: 2,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 519,
        position: 3,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 283,
        position: 4,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 5,
        position: 5,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 216,
        position: 6,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 664,
        position: 7,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 134,
        position: 8,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 60,
        position: 9,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 343,
        position: 10,
        multiplier: 2,
        is_captain: false,
        is_vice_captain: true,
      },
      {
        element: 314,
        position: 11,
        multiplier: 1,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 263,
        position: 12,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 344,
        position: 13,
        multiplier: 0,
        is_captain: true,
        is_vice_captain: false,
      },
      {
        element: 419,
        position: 14,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
      {
        element: 308,
        position: 15,
        multiplier: 0,
        is_captain: false,
        is_vice_captain: false,
      },
    ],
  },
];
export default picks;
